### ISSUE TITLE
RemovedInDjango19Warning: django.utils.importlib will be removed

### ISSUE THREAD

**Issue by midnightlynx** [joestump/django-ajax#66]
ajax/views.py and ajax/utils.py import from django.utils.importlib, which will be going away in Django 1.9.

Since Django 1.8 is just on the verge of release, there's still plenty of time to work on a fix before 1.9 shows up.

**Comment by midnightlynx** [comment]
PR submitted to fix this.

**Comment by nicholasserra** [comment]
Fixed in #69
